# Generated by Django 6.1.1 on 2026-09-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='nom',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
