# Generated by Django 6.1.1 on 2026-10-06 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_organisme', models.CharField(max_length=150)),
                ('responsable_prenom', models.CharField(max_length=100)),
                ('responsable_nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('statut', models.CharField(choices=[('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAYEE', 'Payée')], default='EN_ATTENTE_PAIEMENT', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_inscription', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('montant', models.PositiveIntegerField()),
                ('reference_transaction', models.CharField(max_length=30, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='tenants.demandeinscription')),
            ],
        ),
    ]
