# Generated by Django 6.1.1 on 2026-09-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='pedagogie.formation')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='pedagogie.module')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='pedagogie.formation')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('tenant', 'nom'), name='unique_formation_par_tenant'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('formation', 'nom'), name='unique_module_par_formation'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('formation', 'ordre'), name='unique_ordre_module_par_formation'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('ordre__gte', 1)), name='check_module_ordre_positif'),
        ),
        migrations.AddConstraint(
            model_name='competence',
            constraint=models.UniqueConstraint(fields=('module', 'nom'), name='unique_competence_par_module'),
        ),
        migrations.AddConstraint(
            model_name='competence',
            constraint=models.UniqueConstraint(fields=('module', 'ordre'), name='unique_ordre_competence_par_module'),
        ),
        migrations.AddConstraint(
            model_name='competence',
            constraint=models.CheckConstraint(condition=models.Q(('ordre__gte', 1)), name='check_competence_ordre_positif'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(fields=('formation', 'nom'), name='unique_promotion_par_formation'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='check_promotion_dates'),
        ),
    ]
