# Generated by Django 6.1.1 on 2026-09-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0001_initial'),
        ('tenants', '0002_alter_tenant_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='tenants.tenant')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='pedagogie.competence')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='pedagogie.niveau')),
            ],
            options={
                'ordering': ['niveau__ordre', 'competence__ordre'],
            },
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(fields=('tenant', 'nom'), name='unique_niveau_par_tenant'),
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(fields=('tenant', 'ordre'), name='unique_ordre_niveau_par_tenant'),
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.CheckConstraint(condition=models.Q(('ordre__gte', 1)), name='check_niveau_ordre_positif'),
        ),
        migrations.AddConstraint(
            model_name='competenceniveau',
            constraint=models.UniqueConstraint(fields=('competence', 'niveau'), name='unique_competence_niveau'),
        ),
    ]
