# Generated by Django 6.1.1 on 2026-09-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0002_niveau_competenceniveau_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='pedagogie.promotion')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='GroupeMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances_groupes', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='pedagogie.groupe')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AddField(
            model_name='groupe',
            name='apprenants',
            field=models.ManyToManyField(blank=True, related_name='groupes_pedagogiques', through='pedagogie.GroupeMembre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InscriptionPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_desinscription', models.DateTimeField(blank=True, null=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_promotions', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='pedagogie.promotion')),
            ],
            options={
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupemembre',
            constraint=models.UniqueConstraint(fields=('groupe', 'apprenant'), name='unique_apprenant_par_groupe'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(fields=('promotion', 'nom'), name='unique_groupe_par_promotion'),
        ),
        migrations.AddConstraint(
            model_name='inscriptionpromotion',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('apprenant',), name='unique_promotion_active_par_apprenant'),
        ),
        migrations.AddConstraint(
            model_name='inscriptionpromotion',
            constraint=models.UniqueConstraint(fields=('promotion', 'apprenant'), name='unique_apprenant_par_promotion'),
        ),
    ]
