# Generated by Django 6.1.1 on 2026-09-26 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0003_groupe_groupemembre_groupe_apprenants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormateurPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_formateur', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formateurs_affectes', to='pedagogie.promotion')),
            ],
            options={
                'ordering': ['-date_ajout'],
                'constraints': [models.UniqueConstraint(fields=('formateur', 'promotion'), name='unique_formateur_par_promotion')],
            },
        ),
    ]
