# Generated by Django 6.1.1 on 2026-09-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0005_inscription_par_tenant_et_cloture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveau',
            name='description',
        ),
    ]
