# Generated by Django 6.1.1 on 2026-09-17 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountactivationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivationtoken',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
