# Generated by Django 6.1.1 on 2026-09-26 18:25

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountactivationtoken_date_expiration'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email_insensible_casse'),
        ),
    ]
