# Generated by Django 6.1.1 on 2026-10-02 10:19

import django.db.models.deletion
import revision.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0016_commentaires_pairs'),
        ('pedagogie', '0006_niveau_sans_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('intitule', models.TextField()),
                ('type', models.CharField(choices=[('CHOIX_UNIQUE', 'Choix unique'), ('CHOIX_MULTIPLE', 'Choix multiple')], max_length=20)),
                ('explication', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('texte', models.TextField()),
                ('est_correcte', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='revision.question')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUIZ', 'Quiz'), ('FICHE', 'Fiche de révision')], max_length=10)),
                ('difficulte', models.CharField(blank=True, choices=[('FACILE', 'Facile'), ('MOYEN', 'Moyen'), ('DIFFICILE', 'Difficile')], max_length=10)),
                ('nb_questions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('contenu', models.JSONField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'Génération en cours'), ('ECHEC', 'Échec de la génération'), ('BROUILLON', 'À relire'), ('PUBLIE', 'Publié')], default='EN_COURS', max_length=10)),
                ('erreur', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports_revision_crees', to=settings.AUTH_USER_MODEL)),
                ('fichiers_livrables', models.ManyToManyField(blank=True, related_name='supports_revision', to='activites.fichierlivrable')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='supports_revision', to='pedagogie.module')),
                ('ressources', models.ManyToManyField(blank=True, related_name='supports_revision', to='activites.ressource')),
            ],
            options={
                'ordering': ['type', 'difficulte', 'date_creation'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='revision.supportrevision'),
        ),
        migrations.CreateModel(
            name='FichierSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to=revision.models.chemin_source)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_ajoutes', to='revision.supportrevision')),
            ],
        ),
        migrations.CreateModel(
            name='Tentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponses', models.JSONField(default=dict)),
                ('score', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_quiz', to=settings.AUTH_USER_MODEL)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='revision.supportrevision')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='supportrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'QUIZ')), fields=('module', 'difficulte'), name='un_quiz_par_difficulte_et_module'),
        ),
        migrations.AddConstraint(
            model_name='supportrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('difficulte__in', ['FACILE', 'MOYEN', 'DIFFICILE']), ('type', 'QUIZ')), models.Q(('difficulte', ''), ('type', 'FICHE')), _connector='OR'), name='support_difficulte_selon_type'),
        ),
    ]
