# Generated by Django 6.1.1 on 2026-09-21 11:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogie', '0003_groupe_groupemembre_groupe_apprenants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('consignes', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_limite', models.DateTimeField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('competences', models.ManyToManyField(blank=True, related_name='briefs', to='pedagogie.competence')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='pedagogie.promotion')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='pedagogie.groupe')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='activites.brief')),
            ],
        ),
        migrations.CreateModel(
            name='RessourceBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='briefs/ressources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt'])])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='activites.brief')),
            ],
        ),
        migrations.AddConstraint(
            model_name='brief',
            constraint=models.CheckConstraint(condition=models.Q(('date_limite__gte', models.F('date_debut'))), name='brief_date_limite_gte_date_debut'),
        ),
        migrations.AddConstraint(
            model_name='assignation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('apprenant__isnull', True), ('groupe__isnull', False)), models.Q(('apprenant__isnull', False), ('groupe__isnull', True)), _connector='OR'), name='assignation_exactement_une_cible'),
        ),
        migrations.AddConstraint(
            model_name='assignation',
            constraint=models.UniqueConstraint(condition=models.Q(('groupe__isnull', False)), fields=('brief', 'groupe'), name='unique_assignation_brief_groupe'),
        ),
        migrations.AddConstraint(
            model_name='assignation',
            constraint=models.UniqueConstraint(condition=models.Q(('apprenant__isnull', False)), fields=('brief', 'apprenant'), name='unique_assignation_brief_apprenant'),
        ),
        migrations.AddConstraint(
            model_name='ressourcebrief',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fichier__isnull', True), ('url__isnull', False)), models.Q(('fichier__isnull', False), ('url__isnull', True)), _connector='OR'), name='ressource_brief_exactement_une_source'),
        ),
    ]
