# Generated by Django 6.1.1 on 2026-09-21 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('INVALIDE', 'Invalide'), ('RETENU', 'Retenu')], default='SOUMIS', max_length=20)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('assignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='activites.assignation')),
                ('deposant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livrables_deposes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichierLivrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='livrables/')),
                ('url', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('livrable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='activites.livrable')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('fichier__isnull', False), ('url__isnull', True)), models.Q(('fichier__isnull', True), ('url__isnull', False)), _connector='OR'), name='fichier_livrable_exactement_une_source')],
            },
        ),
    ]
