# Generated by Django 6.1.1 on 2026-09-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_livrable_fichierlivrable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ressourcebrief',
            name='ressource_brief_exactement_une_source',
        ),
        migrations.AddConstraint(
            model_name='ressourcebrief',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fichier', ''), ('url__gt', ''), ('url__isnull', False)), models.Q(('fichier__gt', ''), ('url__isnull', True)), _connector='OR'), name='ressource_brief_exactement_une_source'),
        ),
    ]
