# Generated by Django 6.1.1 on 2026-09-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0003_remove_ressourcebrief_ressource_brief_exactement_une_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fichierlivrable',
            name='fichier_livrable_exactement_une_source',
        ),
        migrations.AddConstraint(
            model_name='fichierlivrable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fichier__gt', ''), ('fichier__isnull', False), ('url__isnull', True)), models.Q(('fichier__isnull', True), ('url__gt', ''), ('url__isnull', False)), _connector='OR'), name='fichier_livrable_exactement_une_source'),
        ),
    ]
