# Generated by Django 6.1.1 on 2026-09-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0004_remove_fichierlivrable_fichier_livrable_exactement_une_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fichierlivrable',
            name='fichier_livrable_exactement_une_source',
        ),
        migrations.AddConstraint(
            model_name='fichierlivrable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('url__isnull', False), models.Q(('url', ''), _negated=True), models.Q(('fichier__isnull', True), ('fichier', ''), _connector='OR')), models.Q(('fichier__isnull', False), models.Q(('fichier', ''), _negated=True), models.Q(('url__isnull', True), ('url', ''), _connector='OR')), _connector='OR'), name='fichier_livrable_exactement_une_source'),
        ),
    ]
