# Generated by Django 6.1.1 on 2026-09-26 07:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0005_remove_fichierlivrable_fichier_livrable_exactement_une_source_and_more'),
        ('tenants', '0002_alter_tenant_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierlivrable',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='livrables/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pptx', 'docx', 'txt'])]),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pptx', 'docx', 'txt'])])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_creees', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date_creation'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('fichier', ''), ('url__gt', ''), ('url__isnull', False)), models.Q(('fichier__gt', ''), ('url__isnull', True)), _connector='OR'), name='ressource_exactement_une_source')],
            },
        ),
    ]
