# Generated by Django 6.1.1 on 2026-09-26 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0006_add_ressource_update_fichier_livrable'),
        ('pedagogie', '0004_add_formateur_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignation',
            name='assignation_exactement_une_cible',
        ),
        migrations.AddConstraint(
            model_name='assignation',
            constraint=models.CheckConstraint(condition=models.Q(('groupe__isnull', False), ('apprenant__isnull', False), _connector='OR'), name='assignation_au_moins_une_cible'),
        ),
    ]
