# Generated by Django 6.1.1 on 2026-09-28 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def terminer_vers_archive(apps, schema_editor):
    """Le statut « Terminé » disparaît : les briefs concernés passent en « Archivé »."""
    Brief = apps.get_model("activites", "Brief")
    Brief.objects.filter(statut="TERMINE").update(statut="ARCHIVE")


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0007_assignation_au_moins_une_cible'),
        ('pedagogie', '0006_niveau_sans_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(terminer_vers_archive, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='ressourcebrief',
            name='ressource_brief_exactement_une_source',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='competences',
        ),
        migrations.AddField(
            model_name='brief',
            name='competence_niveaux',
            field=models.ManyToManyField(blank=True, related_name='briefs', to='pedagogie.competenceniveau'),
        ),
        migrations.AddField(
            model_name='brief',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brief',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='pedagogie.module'),
        ),
        migrations.AddField(
            model_name='brief',
            name='ressources',
            field=models.ManyToManyField(blank=True, related_name='briefs', to='activites.ressource'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20),
        ),
        migrations.DeleteModel(
            name='RessourceBrief',
        ),
        # Module rendu obligatoire (aucun brief existant sans module)
        migrations.AlterField(
            model_name='brief',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='pedagogie.module'),
        ),
    ]
