# Generated by Django 6.1.1 on 2026-09-28 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0008_brief_module_competence_niveaux_ressources'),
        ('pedagogie', '0006_niveau_sans_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='briefs', to='pedagogie.module'),
        ),
    ]
