# Generated by Django 6.1.1 on 2026-09-28 06:24

from django.db import migrations, models


def consignes_vers_contexte(apps, schema_editor):
    """Les anciennes consignes (texte simple) sont reprises dans « Contexte »."""
    from html import escape

    Brief = apps.get_model("activites", "Brief")
    for brief in Brief.objects.exclude(consignes=""):
        paragraphes = [p for p in brief.consignes.split("\n") if p.strip()]
        brief.contexte = "".join(f"<p>{escape(p)}</p>" for p in paragraphes)
        brief.save(update_fields=["contexte"])


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0009_brief_module_restrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='contexte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brief',
            name='criteres_performance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brief',
            name='livrables_attendus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brief',
            name='modalites_evaluation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brief',
            name='modalites_pedagogiques',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(consignes_vers_contexte, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='brief',
            name='consignes',
        ),
    ]
