# Generated by Django 6.1.1 on 2026-09-28 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0010_brief_sections_texte_riche'),
        ('tenants', '0002_alter_tenant_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_briefs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='brief',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='briefs', to='activites.categoriebrief'),
        ),
        migrations.AddConstraint(
            model_name='categoriebrief',
            constraint=models.UniqueConstraint(fields=('tenant', 'nom'), name='unique_categorie_brief_par_tenant'),
        ),
    ]
