# Generated by Django 6.1.1 on 2026-09-28 14:24

import activites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0012_livrable_depots_et_stockage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierlivrable',
            name='apercu',
            field=models.FileField(blank=True, null=True, upload_to=activites.models.chemin_apercu),
        ),
        migrations.AddField(
            model_name='fichierlivrable',
            name='apercu_statut',
            field=models.CharField(blank=True, choices=[('EN_COURS', 'En préparation'), ('PRET', 'Prêt'), ('ECHEC', 'Échec')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ressource',
            name='apercu',
            field=models.FileField(blank=True, null=True, upload_to=activites.models.chemin_apercu),
        ),
        migrations.AddField(
            model_name='ressource',
            name='apercu_statut',
            field=models.CharField(blank=True, choices=[('EN_COURS', 'En préparation'), ('PRET', 'Prêt'), ('ECHEC', 'Échec')], default='', max_length=10),
        ),
    ]
