# Generated by Django 6.1.1 on 2026-09-28 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0013_apercus_office'),
        ('pedagogie', '0006_niveau_sans_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('assignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='activites.assignation')),
                ('evaluateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_faites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceValidee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_validees', to=settings.AUTH_USER_MODEL)),
                ('competence_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='pedagogie.competenceniveau')),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='activites.evaluation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('apprenant', 'competence_niveau'), name='competence_validee_unique')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquis', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('competence_niveau', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evaluations', to='pedagogie.competenceniveau')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='activites.evaluation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'competence_niveau'), name='evaluation_competence_unique')],
            },
        ),
    ]
